### ISSUE TITLE
ONIX and Neuropixel 2.0 Bonsai Questions

### ISSUE THREAD

**Issue by kaylanguyen1** [open-ephys/onix-docs#71]
I was recently following your steps on how to use Bonsai to automate commutation, and I ran into an issue towards the end of the process. We copied the Bonsai workflow from the GitHub Commutators page, but didn't know where to find our Device ID and Address and hence ran into some errors.  The following attachment depicts the errors we received when running the unchanged code. Additionally, we've attached our unchanged workflow. There is one difference between the workflow we got from the Commutator website and what's shown on the website, which is a lack of a Commutator Serial Port in the Configuration property. Where would we be able to find the Device ID and Address, and is there any documentation concerning this? Is there any other documentation concerning Bonsai's interaction with Neuropixel? 
![Outlook-jhldye5h](https://github.com/user-attachments/assets/02d877e0-959f-4e8c-ad5c-b40783886048)

![Outlook-tbn1wxpo](https://github.com/user-attachments/assets/10dd81a7-fae1-4a5f-a4e2-649077f85537)

**Comment by bparks13** [comment]
HI @kaylanguyen1, we have actually migrated to a new library (`OpenEphys.Onix1`), and the new documentation for that can be found [here](https://open-ephys.github.io/bonsai-onix1-docs/).

I would recommend checking out the new library, and seeing if that helps out at all. It seems like you are trying to work with Neuropixels 2.0 commutation, so I would recommend checking out [this page](https://open-ephys.github.io/bonsai-onix1-docs/articles/hardware/np2e/bno055.html) once you have a handle on how to interface with the new library.

For now, I am going to close this issue since we have deprecated the old library and are not actively supporting it any longer. Please feel free to reach out if you have any further questions!
